name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout
        uses: actions/setup-node@v2.4.0
        id: sm_tag
        run: node ./release_output.js

      - name: Check output
        env:
          SM_VERSION: ${{ steps.sm_tag.outputs.tag }}
      
      - name: Core
        uses: actions/setup-node@v2.4.0
        run: |
          npm i -g yarn
          yarn
          yarn build:win
          yarn installer:win

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./installers/secman_desktop-$SM_VERSION-setup.msi"
