name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: |
          node ./scripts/release_output.js
          gh gist clone ${{ secrets.GID }} core/renderer/contents/Home/Sidebar/sms

          yarn build

      - name: Rename Installer
        run: |
          $tag_name=(cat version).replace(' ','')
          mv './build/Secman Desktop Setup $tag_name.exe' ./installers/secman-desktop-setup.exe

      - name: Upload It
        uses: softprops/action-gh-release@v1
        with:
          files: ./installers/secman-desktop-setup.exe

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: |
          gh gist clone ${{ secrets.GID }} core/renderer/contents/Home/Sidebar/sms

          yarn build:darwin

      - name: Create Installer
        run: yarn installer:darwin

      - name: Rename Installer
        run: mv "./installers/Secman Desktop.dmg" ./installers/secman-desktop-setup.dmg

      - name: Upload It
        uses: softprops/action-gh-release@v1
        with:
          files: ./installers/secman-desktop-setup.dmg

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          yarn
          sudo apt-get install fakeroot rpm -y

      - name: Build
        run: |
          node ./scripts/release_output.js
          gh gist clone ${{ secrets.GID }} core/renderer/contents/Home/Sidebar/sms

          yarn build

      - name: Rename Files
        run: |
          export tag_name=$(cat version)
          mv ./build/secman-desktop_${tag_name}_amd64.deb ./installers/secman-desktop-setup-amd64.deb
          mv ./build/secman-desktop-$tag_name-1.amd64.rpm ./installers/secman-desktop-setup-amd64.rpm
          mv "./build/Secman Desktop-$tag_name.AppImage" ./build/secman-desktop.AppImage

      - name: Upload It
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./installers/secman-desktop-setup-amd64.deb
            ./installers/secman-desktop-setup-amd64.rpm
            ./build/secman-desktop.AppImage

