name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: |
          node ./release_output.js
          yarn build:win

      - name: Create Installer
        run: yarn installer:win

      - name: Rename Installer
        run: |
          $tag_name=(cat version).replace(' ','')
          mv ./installers/secman_desktop-$tag_name-setup.msi ./installers/secman-desktop-setup.msi

      - name: Upload It
        uses: softprops/action-gh-release@v1
        with:
          files: ./installers/secman-desktop-setup.msi

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build:darwin

      - name: Create Installer
        run: yarn installer:darwin

      - name: Rename Installer
        run: mv ./installers/Secman Desktop.dmg ./installers/secman-desktop-setup.dmg

      - name: Upload It
        uses: softprops/action-gh-release@v1
        with:
          files: ./installers/secman-desktop-setup.dmg

  deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install Dependencies
        run: |
          yarn
          sudo apt-get install fakeroot -y

      - name: Build
        run: |
          node ./release_output.js
          yarn build:linux

      - name: Create Installer
        run: yarn installer:deb

      - name: Rename Installer
        run: |
          export tag_name=$(cat version)
          mv ./installers/secman-desktop_${tag_name}_amd64.deb ./installers/secman-desktop-setup.deb

      - name: Upload It
        uses: softprops/action-gh-release@v1
        with:
          files: ./installers/secman-desktop-setup.deb

  rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install Dependencies
        run: |
          yarn
          sudo apt-get install rpm -y

      - name: Build
        run: |
          node ./release_output.js
          yarn build:linux

      - name: Create Installer
        run: yarn installer:rpm

      - name: Rename Installer
        run: |
          export tag_name=$(cat version)
          mv ./installers/secman-desktop-$tag_name-1.amd64.rpm ./installers/secman-desktop-setup.rpm

      - name: Upload It
        uses: softprops/action-gh-release@v1
        with:
          files: ./installers/secman-desktop-setup.rpm

  appImage:
    needs: [ deb, rpm ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: |
          node ./release_output.js
          yarn build

      - name: Rename AppImage File
        run: |
          export tag_name=$(cat version)
          mv ./build/Secman Desktop-$tag_name.AppImage ./build/secman-desktop.AppImage

      - name: Upload It
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/secman-desktop.AppImage
